### ISSUE TITLE
Get and maintain an SSL certificate from the LetsEncrypt initiative

### ISSUE THREAD

**Issue by TYoung86** [localtest-dot-me/localtest-dot-me.github.com#3]
Check out https://letsencrypt.org/ ( https://github.com/certbot/certbot/wiki/Links )

Provide a location for the latest certificate (updated on a schedule) for the localtest.me domain, until wildcard support happens?

You'd probably want to use the DNS challenge method, seeing as it'd be quite hard to host files to be read from 127.0.0.1. :+1:

**Comment by dgadelha** [comment]
I was going to suggest that.

**Comment by TYoung86** [comment]
Maybe @aaronpowell or @tathamoddie ?

**Comment by DracoBlue** [comment]
Good idea!

**Comment by Iiridayn** [comment]
Yep, came here to suggest the same thing ;).

**Comment by Sebazzz** [comment]
Wildcard support is in beta. I hope localtest.me will adopt this.

**Comment by SeyZ** [comment]
Any update on this?

**Comment by tathamoddie** [comment]
I don't see any good way to implement this. CAs are required to revoke the certificate if they know that the private key has been compromised. Private key on the internet = compromised. It doesn't matter what the target address is, they are just required to nuke it.

**Comment by kentcdodds** [comment]
I'm trying to do something like this myself. Can you help me understand why the private key would have to be "on the internet" for this to work?

**Comment by tathamoddie** [comment]
We can totally secure https://readme.localtest.me. (It already is.)

But not the rest of localtest.me.

If we did this via a traditional CA, then we'd get a private key. You can't use this for your own testing unless we give you the private key. Now we're distributing the private key. CAs say this is bad, because it means the certificate has been compromised. As soon as they see distribution, they nuke the certificate. Back to step 0. (We've tried this route before.)

To do this with an automated CA like Let's Encrypt, you need to [prove control of the domain](https://letsencrypt.org/how-it-works/#domain-validation).

This can be done via DNS. I control the DNS zone though, not you as an end user. If I did the authorisation, then handed you key (so you could use the certificate), then it's the same scenario as above. Doesn't work.

This can also be done via responding to a well-known URI, like `https://localtest.me/acme/chall/prV_B7yEyA4`. Except when Let's Encrypt goes to try and call `localtest.me` to request that resource, they'll resolve the address as `::1` and just loop back to themselves. They'll never hit your test application. Verification fails. Doesn't work.

There's a very relevant write-up here: https://letsencrypt.org/docs/certificates-for-localhost/

Hope that helps!

**Comment by kentcdodds** [comment]
That was very helpful! Thank you for taking the time to explain that to me :)
